version: '3'
services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        volumes:
          - ./db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root_password
    app:
      container_name: tomcat
      image: tomcat:8.5-jdk8-adoptopenjdk-openj9
      ports:
        - 8080:8080
      volumes:
        - ./webapps:/usr/local/tomcat/webapps
volumes:
    db_data:
    webapps: